services:
  jupyter:
    image: lando-full
    container_name: lando-lab
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/jovyan/work
      - ../src/tmp_host:/tmp
    environment:
      - PYDEVD_DISABLE_FILE_VALIDATION=1
      - TMPDIR=/tmp
    command: start-notebook.py --NotebookApp.token='' --NotebookApp.default_url=/lab/tree/LANDO.ipynb
